steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/who-arcgis:1.0.0-qa$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/who-arcgis:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/who-arcgis:1.0.0-qa$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/who-arcgis:latest"]
