name: Docker Image

on:
    release:
        types:
            - created

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: praekeltfoundation/turnio-who-arcgis
            tag_with_ref: true
            tag_with_sha: true
